baseurl = "http://jamesskemp.github.io/words/"
languageCode = "en-us"
title = "James Skemp's Test Hugo-Generated Site"
theme = "beg"
publishdir = "public"
canonifyurls = true

[params]
googleAnalytics = "UA-541034-4"
googleadsense = "ca-pub-3526066001929698"
googleadsenseslot = "3689523691"
disqus = "strivinglife"
twitter = ""
googleplus = ""
linkedin = ""
youtube = ""
paypal = ""
amazonwishlist = "http://amzn.to/22xk0cK"
